#!/usr/bin/env bash
# Print CLI usage summary. Dispatched as: filesync | filesync help | -h | --help
set -euo pipefail

_w=22
_hr() { printf '  %-*s  %s\n' "$_w" "$1" "$2"; }
_hm() { printf '%*s%s\n' $((2 + _w + 2)) '' "$1"; }

echo 'Usage:  filesync [-V | --version]'
echo '       filesync [help | -h | --help]'
echo '       filesync <command> [arguments]'
echo ''
echo 'Map and sync files across git checkouts (.filesync/ per project).'
echo ''
echo 'Project setup:'
_hr 'init' '[directory] Create .filesync/ (default: cwd); establishes project root'
_hr 'enable' 'Turn file sync on in merged config'
_hr 'disable' 'Turn file sync off in merged config'
_hr 'path-mode' '[relative|absolute] Show or set repo path resolution mode'
_hr 'progress' '[hidden|bar|percent] TTY progress on long loops (default percent)'
_hr 'show-progress' 'Same as progress bar (legacy alias)'
_hr 'hide-progress' 'Same as progress hidden (legacy alias)'
echo ''
echo 'Inspect and sync:'
_hr 'check (c)' '[--repo=] [--file=] [--status=] Verify mappings; refresh row status'
_hr 'sync (s)' '[--repo=] [--file=] [--dry-run] [--force] [--showall] [--status=] [--include-detached|…]'
_hm 'Copy from masters into the project; update files.json'
_hr 'list-repos (lr)' '[--repo=] List configured repos (alias: repos)'
_hr 'list-files (lf)' '[--repo=] [--file=] [--status=] [--include-detached] List mappings'
_hm 'Aliases: list, files'
echo ''
echo 'Mappings and repos:'
_hr 'add-file (af)' '<repo> <path_in_repo>[:<local_path>] … [--mark-master] [--also=…]'
_hm 'Track from repo checkout; path_in_repo is under the repo; omit :local if same path'
_hr 'add-master (am)' '<repo> <local_path>[:<path_in_repo>] … [--also=…]'
_hm 'Promote local file to master; omit :path_in_repo if it matches local_path'
_hr 'add-clone (ac)' '<target_repo> <master_path>[:<local_path>] … [--also=…]'
_hm 'Clone from kind=master in this project into sibling(s); fails if target exists'
_hr 'push' '[--all] [<local_path> …] Push local content to linked master paths'
_hr 'detach-file (ddf)' '<local_path> … Set detached status and kind=detached marker'
_hr 'attach-file (daf)' '<local_path> … Re-couple detached rows; check each'
_hr 'detach-repo (ddr)' '<repo_name> Detach every mapping for that repo'
_hr 'attach-repo (dar)' '<repo_name> Attach every mapping for that repo'
_hr 'remove-file (rmf)' '<local_path> … Drop row; strip clone/detached marker; keep master'
_hr 'remove-repo (rmr)' '<repo_name> [-y] Drop repo (prompts if file mappings remain; -y skips prompt)'
_hr 'add-repo (ar)' 'Interactively add a repo (alias: repo)'
_hr 'edit-repo (er)' '<name> [--rename=] [--path=] [--url=] [--branch=] (alias: repo-edit)'
_hm 'Rename updates repo_name in all files.json rows and marker lines'
echo ''
echo 'Self-update:'
_hr 'update' '[-y] Check GitHub for newer release; prompt to install if available (git or .deb)'
echo ''
echo 'Help:'
_hr 'help' 'Print this summary (-h, --help)'
echo ''
echo 'Status filters (sync, check, list-files; --status= comma-separated, OR):'
_hm 'Special tokens: unset (empty field), all (non-detached unless --include-detached), error (any error_*), detached.'
_hm 'Default sync (no --status=): unset, sync_required, error_missing_local; detached skipped unless --include-detached.'
_hm 'With --force: also local_newer and conflict. Other tokens: synced, conflict, detached, error_* (see man page).'
echo ''
echo 'Config:'
_hm 'Discovered like git: walk up from cwd for .filesync/ (config.json, repos.json, files.json).'
_hm 'See docs/configuration.md'
